services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/TCAL?authSource=admin
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app

volumes:
  mongo-data:
