# Base image
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY ./client/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY ./client .

# Construire l'application React
RUN npm run build

# Utiliser un serveur HTTP statique pour servir les fichiers construits
RUN npm install -g serve
EXPOSE 3000

# Commande pour démarrer le serveur de l'application React
CMD ["serve", "-s", "build"]
