# Base image
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY ./server/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY ./server .

# Construire le projet TypeScript (si applicable)
RUN npm run build

# Exposer le port utilisé par le backend
EXPOSE 5000

# Commande pour démarrer le backend
CMD ["npm", "start"]
