services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  nodeapp:
    build: .
    container_name: nodeapp
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/TCAL?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    command: npm start

volumes:
  mongo-data:
